//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookLoginTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grocery_list
    {
        public int grocery_id { get; set; }
        public Nullable<int> userid { get; set; }
        public string grocery_item { get; set; }
        public string grocery_amount { get; set; }
    
        public virtual user_list user_list { get; set; }
    }
}
