//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookLoginTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredient
    {
        public int ingredient_id { get; set; }
        public Nullable<int> recipe_id { get; set; }
        public string ingredient_name { get; set; }
        public string ingredient_amount { get; set; }
    
        public virtual recipe recipe { get; set; }
    }
}
