//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookLoginTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post_recipe()
        {
            this.post_ingredient = new HashSet<post_ingredient>();
            this.post_instruction = new HashSet<post_instruction>();
        }
    
        public int post_recipe_id { get; set; }
        public Nullable<int> userid { get; set; }
        public string post_ImageName { get; set; }
        public string post_ImagePath { get; set; }
        public string post_recipe_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post_ingredient> post_ingredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post_instruction> post_instruction { get; set; }
        public virtual user_list user_list { get; set; }
    }
}
