//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookLoginTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_instruction
    {
        public int post_instruction_id { get; set; }
        public Nullable<int> post_recipe_id { get; set; }
        public string post_instruction_detail { get; set; }
    
        public virtual post_recipe post_recipe { get; set; }
    }
}
