//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookLoginTesting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cookingapp_latestEntities : DbContext
    {
        public cookingapp_latestEntities()
            : base("name=cookingapp_latestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<calorie> calories { get; set; }
        public virtual DbSet<grocery_list> grocery_list { get; set; }
        public virtual DbSet<ingredient> ingredients { get; set; }
        public virtual DbSet<instruction> instructions { get; set; }
        public virtual DbSet<post_ingredient> post_ingredient { get; set; }
        public virtual DbSet<post_instruction> post_instruction { get; set; }
        public virtual DbSet<post_recipe> post_recipe { get; set; }
        public virtual DbSet<recipe> recipes { get; set; }
        public virtual DbSet<user_list> user_list { get; set; }
        public virtual DbSet<fav_recipe> fav_recipe { get; set; }
    }
}
